version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
      - pip install boto3==1.34.42
      - pip install pytest
      - pip install requests      

  pre_build:
    commands:
      - echo "Running pre-deployment actions..."
      - aws s3 cp s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/buildspec-deploy.zip /tmp/buildspec-deploy.zip
      - unzip /tmp/buildspec-deploy.zip -d /tmp/

  build:
    commands:
      - echo "Downloading artifacts from S3..."
      - aws s3 cp s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/CRUDOrders.zip /tmp/CRUDOrders.zip
      - aws s3 cp s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/CRUDWallet.zip /tmp/CRUDWallet.zip
      - aws s3 cp s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/CallBackLambda.zip /tmp/CallBackLambda.zip

      - echo "Updating CRUDOrders Lambda function..."
      - aws lambda update-function-code --function-name CRUDOrders --zip-file fileb:///tmp/CRUDOrders.zip

      - echo "Updating CRUDWallet Lambda function..."
      - aws lambda update-function-code --function-name CRUDWallet --zip-file fileb:///tmp/CRUDWallet.zip

      - echo "Updating CallbackLambda function..."
      - aws lambda update-function-code --function-name CallbackLambda --zip-file fileb:///tmp/CallBackLambda.zip
  
  post_build:
    commands:
      - echo "Running integration tests..."
      - pytest test_crud_orders_lambda_read.py
      - pytest test_crud_orders_lambda_update.py
      - pytest test_crud_wallet_lambda_add_funds.py
      - pytest test_crud_wallet_lambda_get_wallet.py
      - pytest test_crud_wallet_lambda_deduct_funds.py

artifacts:
  files:
    - none
