version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install boto3==1.34.42

  pre_build:
    commands:
      - echo "Running pre-build actions..."
      # Add any pre-build actions here, such as running tests or other checks

  build:
    commands:
      - ls -l
      - echo "Packaging CRUDOrders Lambda function..."
      - cd Functions/CRUDOrders
      - ls -l
      - mkdir -p package
      - cp -r *.py package/
      - cd package
      - ls -l
      - zip -r ../../CRUDOrders.zip .
      - cd ../..

      - ls -l
      - echo "Packaging CRUDWallet Lambda function..."
      - cd CRUDWallet
      - ls -l
      - mkdir -p package
      - cp -r *.py package/
      - cd package
      - ls -l
      - zip -r ../../CRUDWallet.zip .
      - ls -l
      - cd ..
      - ls -l
      - cd ..

      - ls -l
      - echo "Packaging CallBackLambda function..."
      - cd CallBackLambda
      - ls -l
      - mkdir -p package
      - cp -r *.py package/
      - cd package
      - ls -l
      - zip -r ../../CallBackLambda.zip .
      - ls -l
      - cd ..
      - ls -l
      - cd ..
      - cd ..

      - ls -l
      - echo "Packaging CloudFormation stack template..."
      - cd CloudFormatTemplates
      - ls -l
      - zip -r ../stack.zip stack.yml
      - cd ..

  post_build:
    commands:
      - echo "Uploading packaged functions and stack template to S3..."
      - ls -l
      - aws s3 cp stack.zip s3://deployment-ad-system/
      - cd Functions
      - aws s3 cp CRUDOrders.zip s3://deployment-ad-system/
      - aws s3 cp CRUDWallet.zip s3://deployment-ad-system/

artifacts:
  files:
    - ./Functions/CRUDOrders.zip
    - ./Functions/CRUDWallet.zip
    - ./stack.zip

environment:
  variables:
    BUCKET_NAME: "deployment-ad-system"
