version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install boto3==1.34.42

  pre_build:
    commands:
      - echo "Running pre-build actions..."

  build:
    commands:
      - echo "Packaging CRUDOrders Lambda function..."
      - cd Functions/CRUDOrders
      - mkdir -p package
      - cp lambda_function.py package/
      - cp -r *.py package/
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t package/; fi
      - cd package
      - zip -r ../../CRUDOrders.zip .
      - cd ../..

      - echo "Packaging CRUDWallet Lambda function..."
      - cd Functions/CRUDWallet
      - mkdir -p package
      - cp lambda_function.py package/
      - cp -r *.py package/
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t package/; fi
      - cd package
      - zip -r ../../CRUDWallet.zip .
      - cd ../..

      - echo "Packaging CallBackLambda function..."
      - cd Functions/CallBackLambda
      - mkdir -p package
      - cp lambda_function.py package/
      - cp -r *.py package/
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t package/; fi
      - cd package
      - zip -r ../../CallBackLambda.zip .
      - cd ../..

      - echo "Packaging CloudFormation stack template and copying buildspec-deploy.yml..."
      - cd CloudFormatTemplates
      - zip -r ../stack.zip stack.yml
      - cd ..
      - cp buildspec-deploy.yml /tmp/buildspec-deploy.yml

  post_build:
    commands:
      - echo "Uploading packaged functions and stack template to S3..."
      - aws s3 cp buildspec-deploy.yml s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/
      - aws s3 cp stack.zip s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/
      - aws s3 cp Functions/CRUDOrders.zip s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/
      - aws s3 cp Functions/CRUDWallet.zip s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/
      - aws s3 cp Functions/CallBackLambda.zip s3://deployment-ad-system/AdSystemPipeLine/BuildArtif/

artifacts:
  files:
    - stack.zip
    - buildspec-deploy.yml
    - Functions/CRUDOrders.zip
    - Functions/CRUDWallet.zip
    - Functions/CallBackLambda.zip
  discard-paths: yes
  name: BuildArtifact

environment:
  variables:
    BUCKET_NAME: "deployment-ad-system"
